apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: green-deploy
  name: green-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: green-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: green-deploy
        type: frontend
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
         requests:
          cpu: "1"
         limits:
          cpu: "5"
status: {}
